name: adaptive-workspace
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
